name: lightweight_calendar
description: A simple fast table calendar for Flutter.
version: 1.0.4
homepage: https://github.com/CodeRebirth/simple_calendar
license: file://LICENSE

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

